/*
 * @author swadisaurus
 * @dateStarted 30/08/2018
 * @link https://projecteuler.net/problem=2
 * @Question Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

 public class PE_002
 {
   public static void main(String args[])
   {
     int x=0,y=1,z=0, sum=0;//Inittial values to calculate Fibonacci series
     while(z<4000000)//Condition for size of numbers. Must be less than 4 million
     {
       if(z%2==0)//check if even
       {
         sum+=z;//add to sum if even
       }
       z=x+y;//z updated to be sum of previous two terms
       x=y;//x updated to be 2nd last term.
       y=z;//y updated to be last term
     }
     System.out.println(sum);//return final answer
   }
 }
